### ISSUE TITLE
config.json as huggingface model modifier

### ISSUE THREAD

**Issue by aarisr** [paulcjh/gpt-j-6b#7]
I am trying to get this to run on my computer:
I have succesfully converted the _slim model to a torch model.

But the Code for Inferencing is failing me right now.
Here is my issue:

When i run the code - at some point it wants to connect to the api of huggingface.co
somehow the whole config.json gets used as a part of the api request url.

I am not sure whats the problem.
```
https://huggingface.co/%7B'activation_function':%20'gelu_new',%20'architectures':%20%5B'GPTNeoForCausalLM'%5D,%20'attention_dropout':%200,%20'attention_layers':%20%5B'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global'%5D,%20'attention_types':%20%5B%5B%5B'global'%5D,%2028%5D%5D,%20'bos_token_id':%2050256,%20'embed_dropout':%200,%20'eos_token_id':%2050256,%20'gradient_checkpointing':%20False,%20'hidden_size':%204096,%20'initializer_range':%200.02,%20'intermediate_size':%20None,%20'jax':%20True,%20'layer_norm_epsilon':%201e-05,%20'max_position_embeddings':%202048,%20'model_type':%20'gpt_neo',%20'num_heads':%2016,%20'num_layers':%2028,%20'resid_dropout':%200,%20'rotary':%20True,%20'rotary_dim':%2064,%20'summary_activation':%20None,%20'summary_first_dropout':%200.1,%20'summary_proj_to_labels':%20True,%20'summary_type':%20'cls_index',%20'summary_use_proj':%20True,%20'transformers_version':%20'4.5.0.dev0',%20'use_cache':%20True,%20'vocab_size':%2050400,%20'window_size':%20256,%20'tokenizer_class':%20'GPT2Tokenizer',%20'task_specific_params':%20%7B'text-generation':%20%7B'do_sample':%20True,%20'temperature':%201.0,%20'max_length':%2050%7D%7D%7D/resolve/main/config.json
```

```bash
root@3b0623f86e5d:/workspace/gpt-j-hf# ls -lha . && cat inference_test.py && python3 inference_test.py 
total 12G
drwxrwxr-x 2 1000 1000   75 Aug 15 13:02 .
drwxr-xr-x 1 root root   50 Aug 15 12:59 ..
-rw-r--r-- 1 root root 1.4K Aug 15 12:45 config.json
-rwxrwxr-x 1 root root 1.1K Aug 15 13:00 inference_test.py
-rw-r--r-- 1 root root  12G Aug 15 12:32 pytorch_model.bin
```

```python3
import time
import torch
from transformers import GPTNeoForCausalLM, AutoConfig, GPT2Tokenizer
import torch
import transformers
import collections
import json
import os

class Checkpoint(collections.MutableMapping):
    def __init__(self):
        self.checkpoint = torch.load("pytorch_model.bin")
        print("Loaded")
    def __len__(self):
        return len(self.checkpoint)
    def __getitem__(self, key):
        return torch.load(self.checkpoint[key])
    def __setitem__(self, key, value):
        return
    def __delitem__(self, key, value):
        return
    def keys(self):
        return self.checkpoint.keys()
    def __iter__(self):
        for key in self.checkpoint:
            yield (key, self.__getitem__(key))
    def __copy__(self):
        return self.__dict__
    def copy(self):
        return self.__dict__

print("load", flush=True)

with open('config.json', 'r') as f:
    config = json.load(f)


print(config)
model = GPTNeoForCausalLM.from_pretrained(pretrained_model_name_or_path=None, config=config, state_dict=Checkpoint())
print("ok")
model.eval()
```

```bash
inference_test.py:10: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  class Checkpoint(collections.MutableMapping):
load
{'activation_function': 'gelu_new', 'architectures': ['GPTNeoForCausalLM'], 'attention_dropout': 0, 'attention_layers': ['global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global'], 'attention_types': [[['global'], 28]], 'bos_token_id': 50256, 'embed_dropout': 0, 'eos_token_id': 50256, 'gradient_checkpointing': False, 'hidden_size': 4096, 'initializer_range': 0.02, 'intermediate_size': None, 'jax': True, 'layer_norm_epsilon': 1e-05, 'max_position_embeddings': 2048, 'model_type': 'gpt_neo', 'num_heads': 16, 'num_layers': 28, 'resid_dropout': 0, 'rotary': True, 'rotary_dim': 64, 'summary_activation': None, 'summary_first_dropout': 0.1, 'summary_proj_to_labels': True, 'summary_type': 'cls_index', 'summary_use_proj': True, 'transformers_version': '4.5.0.dev0', 'use_cache': True, 'vocab_size': 50400, 'window_size': 256, 'tokenizer_class': 'GPT2Tokenizer', 'task_specific_params': {'text-generation': {'do_sample': True, 'temperature': 1.0, 'max_length': 50}}}
Loaded
404 Client Error: Not Found for url: https://huggingface.co/%7B'activation_function':%20'gelu_new',%20'architectures':%20%5B'GPTNeoForCausalLM'%5D,%20'attention_dropout':%200,%20'attention_layers':%20%5B'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global'%5D,%20'attention_types':%20%5B%5B%5B'global'%5D,%2028%5D%5D,%20'bos_token_id':%2050256,%20'embed_dropout':%200,%20'eos_token_id':%2050256,%20'gradient_checkpointing':%20False,%20'hidden_size':%204096,%20'initializer_range':%200.02,%20'intermediate_size':%20None,%20'jax':%20True,%20'layer_norm_epsilon':%201e-05,%20'max_position_embeddings':%202048,%20'model_type':%20'gpt_neo',%20'num_heads':%2016,%20'num_layers':%2028,%20'resid_dropout':%200,%20'rotary':%20True,%20'rotary_dim':%2064,%20'summary_activation':%20None,%20'summary_first_dropout':%200.1,%20'summary_proj_to_labels':%20True,%20'summary_type':%20'cls_index',%20'summary_use_proj':%20True,%20'transformers_version':%20'4.5.0.dev0',%20'use_cache':%20True,%20'vocab_size':%2050400,%20'window_size':%20256,%20'tokenizer_class':%20'GPT2Tokenizer',%20'task_specific_params':%20%7B'text-generation':%20%7B'do_sample':%20True,%20'temperature':%201.0,%20'max_length':%2050%7D%7D%7D/resolve/main/config.json
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/transformers/configuration_utils.py", line 484, in get_config_dict
    resolved_config_file = cached_path(
  File "/opt/conda/lib/python3.8/site-packages/transformers/file_utils.py", line 1323, in cached_path
    output_path = get_from_cache(
  File "/opt/conda/lib/python3.8/site-packages/transformers/file_utils.py", line 1494, in get_from_cache
    r.raise_for_status()
  File "/opt/conda/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/%7B'activation_function':%20'gelu_new',%20'architectures':%20%5B'GPTNeoForCausalLM'%5D,%20'attention_dropout':%200,%20'attention_layers':%20%5B'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global',%20'global'%5D,%20'attention_types':%20%5B%5B%5B'global'%5D,%2028%5D%5D,%20'bos_token_id':%2050256,%20'embed_dropout':%200,%20'eos_token_id':%2050256,%20'gradient_checkpointing':%20False,%20'hidden_size':%204096,%20'initializer_range':%200.02,%20'intermediate_size':%20None,%20'jax':%20True,%20'layer_norm_epsilon':%201e-05,%20'max_position_embeddings':%202048,%20'model_type':%20'gpt_neo',%20'num_heads':%2016,%20'num_layers':%2028,%20'resid_dropout':%200,%20'rotary':%20True,%20'rotary_dim':%2064,%20'summary_activation':%20None,%20'summary_first_dropout':%200.1,%20'summary_proj_to_labels':%20True,%20'summary_type':%20'cls_index',%20'summary_use_proj':%20True,%20'transformers_version':%20'4.5.0.dev0',%20'use_cache':%20True,%20'vocab_size':%2050400,%20'window_size':%20256,%20'tokenizer_class':%20'GPT2Tokenizer',%20'task_specific_params':%20%7B'text-generation':%20%7B'do_sample':%20True,%20'temperature':%201.0,%20'max_length':%2050%7D%7D%7D/resolve/main/config.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference_test.py", line 39, in <module>
    model = GPTNeoForCausalLM.from_pretrained(pretrained_model_name_or_path=None, config=config, state_dict=Checkpoint())
  File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1067, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/opt/conda/lib/python3.8/site-packages/transformers/configuration_utils.py", line 427, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/configuration_utils.py", line 504, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for '{'activation_function': 'gelu_new', 'architectures': ['GPTNeoForCausalLM'], 'attention_dropout': 0, 'attention_layers': ['global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global'], 'attention_types': [[['global'], 28]], 'bos_token_id': 50256, 'embed_dropout': 0, 'eos_token_id': 50256, 'gradient_checkpointing': False, 'hidden_size': 4096, 'initializer_range': 0.02, 'intermediate_size': None, 'jax': True, 'layer_norm_epsilon': 1e-05, 'max_position_embeddings': 2048, 'model_type': 'gpt_neo', 'num_heads': 16, 'num_layers': 28, 'resid_dropout': 0, 'rotary': True, 'rotary_dim': 64, 'summary_activation': None, 'summary_first_dropout': 0.1, 'summary_proj_to_labels': True, 'summary_type': 'cls_index', 'summary_use_proj': True, 'transformers_version': '4.5.0.dev0', 'use_cache': True, 'vocab_size': 50400, 'window_size': 256, 'tokenizer_class': 'GPT2Tokenizer', 'task_specific_params': {'text-generation': {'do_sample': True, 'temperature': 1.0, 'max_length': 50}}}'. Make sure that:

- '{'activation_function': 'gelu_new', 'architectures': ['GPTNeoForCausalLM'], 'attention_dropout': 0, 'attention_layers': ['global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global'], 'attention_types': [[['global'], 28]], 'bos_token_id': 50256, 'embed_dropout': 0, 'eos_token_id': 50256, 'gradient_checkpointing': False, 'hidden_size': 4096, 'initializer_range': 0.02, 'intermediate_size': None, 'jax': True, 'layer_norm_epsilon': 1e-05, 'max_position_embeddings': 2048, 'model_type': 'gpt_neo', 'num_heads': 16, 'num_layers': 28, 'resid_dropout': 0, 'rotary': True, 'rotary_dim': 64, 'summary_activation': None, 'summary_first_dropout': 0.1, 'summary_proj_to_labels': True, 'summary_type': 'cls_index', 'summary_use_proj': True, 'transformers_version': '4.5.0.dev0', 'use_cache': True, 'vocab_size': 50400, 'window_size': 256, 'tokenizer_class': 'GPT2Tokenizer', 'task_specific_params': {'text-generation': {'do_sample': True, 'temperature': 1.0, 'max_length': 50}}}' is a correct model identifier listed on 'https://huggingface.co/models'

- or '{'activation_function': 'gelu_new', 'architectures': ['GPTNeoForCausalLM'], 'attention_dropout': 0, 'attention_layers': ['global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global', 'global'], 'attention_types': [[['global'], 28]], 'bos_token_id': 50256, 'embed_dropout': 0, 'eos_token_id': 50256, 'gradient_checkpointing': False, 'hidden_size': 4096, 'initializer_range': 0.02, 'intermediate_size': None, 'jax': True, 'layer_norm_epsilon': 1e-05, 'max_position_embeddings': 2048, 'model_type': 'gpt_neo', 'num_heads': 16, 'num_layers': 28, 'resid_dropout': 0, 'rotary': True, 'rotary_dim': 64, 'summary_activation': None, 'summary_first_dropout': 0.1, 'summary_proj_to_labels': True, 'summary_type': 'cls_index', 'summary_use_proj': True, 'transformers_version': '4.5.0.dev0', 'use_cache': True, 'vocab_size': 50400, 'window_size': 256, 'tokenizer_class': 'GPT2Tokenizer', 'task_specific_params': {'text-generation': {'do_sample': True, 'temperature': 1.0, 'max_length': 50}}}' is the correct path to a directory containing a config.json file


root@3b0623f86e5d:/workspace/gpt-j-hf#
```

**Comment by qucheng-gong** [comment]
see issue #1
